export const INIT_SONGS = 'INIT_SONGS'

export const SORT_BY_POSITION_ASC = 'SORT_BY_POSITION_ASC';
export const SORT_BY_POSITION_DESC = 'SORT_BY_POSITION_DESC';
export const SORT_BY_DURATION_ASC = 'SORT_BY_DURATION_ASC';
export const SORT_BY_DURATION_DESC = 'SORT_BY_DURATION_DESC';

export const SHOW_LOADING = 'SHOW_LOADING';
export const SHOW_LIST = 'SHOW_LIST';
export const SHOW_ICONS = 'SHOW_ICONS';